ALTER TABLE admission_forms 
ADD COLUMN reapplied TINYINT(1) DEFAULT 0,
ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS address TEXT NULL;
